#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Game.App
{

/// <summary>JSON-authored text and metadata for evidence generated by cross-system simulation.</summary>
public sealed class EvidenceDefinition
{
    public EvidenceDefinition(string id, string scoutReportText)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Evidence id must not be empty.", nameof(id));
        if (string.IsNullOrWhiteSpace(scoutReportText)) throw new ArgumentException("Scout report text must not be empty.", nameof(scoutReportText));
        Id = id.Trim();
        ScoutReportText = scoutReportText.Trim();
    }

    public string Id { get; }
    public string ScoutReportText { get; }
}

public sealed class EvidenceDefinitionSet
{
    private readonly Dictionary<string, EvidenceDefinition> definitions;

    public EvidenceDefinitionSet(IEnumerable<EvidenceDefinition> definitions)
    {
        this.definitions = (definitions ?? throw new ArgumentNullException(nameof(definitions)))
            .ToDictionary(definition => definition.Id, StringComparer.Ordinal);
    }

    public EvidenceDefinition? Find(string? id)
    {
        return !string.IsNullOrWhiteSpace(id) && definitions.TryGetValue(id, out var definition) ? definition : null;
    }

    public IReadOnlyCollection<EvidenceDefinition> All => definitions.Values;
}

public sealed class CrossSystemDataBundle
{
    public CrossSystemDataBundle(EvidenceDefinitionSet evidence)
    {
        Evidence = evidence ?? throw new ArgumentNullException(nameof(evidence));
    }

    public EvidenceDefinitionSet Evidence { get; }
}

/// <summary>
/// Loads the cross-system content that is shared by world generation, scouting and later reaction
/// resolution. Runtime world state stores only stable definition IDs, never authored player text.
/// </summary>
public static class CrossSystemDataLoader
{
    private const int SupportedSchemaVersion = 1;

    public static CrossSystemDataBundle? LoadFromDirectory(string rootFolder)
    {
        if (string.IsNullOrWhiteSpace(rootFolder) || !Directory.Exists(rootFolder)) return null;

        var documents = Directory.EnumerateFiles(rootFolder, "*.json", SearchOption.AllDirectories)
            .OrderBy(path => path, StringComparer.Ordinal)
            .Select(File.ReadAllText)
            .ToList();
        return documents.Count == 0 ? null : LoadFromJson(documents);
    }

    public static CrossSystemDataBundle LoadFromJson(IEnumerable<string> jsonDocuments)
    {
        if (jsonDocuments == null) throw new ArgumentNullException(nameof(jsonDocuments));
        var evidence = new List<EvidenceDefinitionDto>();

        foreach (var json in jsonDocuments)
        {
            JObject envelope;
            try
            {
                envelope = JObject.Parse(json);
            }
            catch (JsonException ex)
            {
                throw new LocationDataException($"Malformed cross-system JSON document: {ex.Message}");
            }

            var schemaVersion = (int?)envelope["schemaVersion"] ?? 0;
            if (schemaVersion != SupportedSchemaVersion)
            {
                throw new LocationDataException($"Unsupported schemaVersion '{schemaVersion}' (expected {SupportedSchemaVersion}).");
            }

            var items = envelope["items"] as JArray ?? new JArray();
            if ((string?)envelope["documentType"] != "evidence-definitions")
            {
                throw new LocationDataException($"Unsupported cross-system documentType '{(string?)envelope["documentType"]}'.");
            }

            evidence.AddRange(items.ToObject<List<EvidenceDefinitionDto>>()!);
        }

        var definitions = evidence.Select(item => new EvidenceDefinition(Require(item.Id, "evidence.id"), Require(item.ScoutReportText, "evidence.scoutReportText"))).ToList();
        if (definitions.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Cross-system evidence IDs must be unique.");
        }

        return new CrossSystemDataBundle(new EvidenceDefinitionSet(definitions));
    }

    private static string Require(string? value, string field)
    {
        if (string.IsNullOrWhiteSpace(value)) throw new LocationDataException($"Missing required field '{field}'.");
        return value.Trim();
    }

    private sealed class EvidenceDefinitionDto
    {
        public string? Id { get; set; }
        public string? ScoutReportText { get; set; }
    }
}
}
