#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Game.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Game.App
{

/// <summary>JSON-authored text and metadata for evidence generated by cross-system simulation.</summary>
public sealed class EvidenceDefinition
{
    public EvidenceDefinition(string id, string scoutReportText, string? worldEventText = null, string? symbolId = null)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Evidence id must not be empty.", nameof(id));
        if (string.IsNullOrWhiteSpace(scoutReportText)) throw new ArgumentException("Scout report text must not be empty.", nameof(scoutReportText));
        Id = id.Trim();
        ScoutReportText = scoutReportText.Trim();
        WorldEventText = string.IsNullOrWhiteSpace(worldEventText) ? null : worldEventText.Trim();
        SymbolId = string.IsNullOrWhiteSpace(symbolId) ? null : symbolId.Trim();
    }

    public string Id { get; }
    public string ScoutReportText { get; }
    public string? WorldEventText { get; }
    /// <summary>Neutral recurring-signature ID; it never exposes the owning generated faction.</summary>
    public string? SymbolId { get; }
}

/// <summary>Authoring metadata for a recurring sign that the archive may connect across reports.</summary>
public sealed class FactionSignatureDefinition
{
    public FactionSignatureDefinition(string id, string profileId, string label)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Signature id must not be empty.", nameof(id));
        if (string.IsNullOrWhiteSpace(profileId)) throw new ArgumentException("Signature profile id must not be empty.", nameof(profileId));
        if (string.IsNullOrWhiteSpace(label)) throw new ArgumentException("Signature label must not be empty.", nameof(label));
        Id = id.Trim();
        ProfileId = profileId.Trim();
        Label = label.Trim();
    }

    public string Id { get; }
    public string ProfileId { get; }
    public string Label { get; }
}

/// <summary>
/// Reusable faction behaviour profile. It describes a generated faction's values without ever
/// assigning that profile to a concrete location or generated faction instance in static content.
/// </summary>
public sealed class FactionProfileDefinition
{
    private readonly List<string> values;
    private readonly List<string> tabooActionTags;
    private readonly List<string> observationChannels;

    public FactionProfileDefinition(
        string id,
        string label,
        IEnumerable<string>? values = null,
        IEnumerable<string>? tabooActionTags = null,
        FactionTerritorialPolicyDefinition? territorialPolicy = null,
        string? contactStyle = null,
        string? leadershipStyle = null,
        int observationRange = 0,
        IEnumerable<string>? observationChannels = null)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Faction profile id must not be empty.", nameof(id));
        if (string.IsNullOrWhiteSpace(label)) throw new ArgumentException("Faction profile label must not be empty.", nameof(label));
        Id = id.Trim();
        Label = label.Trim();
        this.values = (values ?? Enumerable.Empty<string>())
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();
        this.tabooActionTags = (tabooActionTags ?? Enumerable.Empty<string>())
            .Where(tag => !string.IsNullOrWhiteSpace(tag))
            .Select(tag => tag.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();
        if (observationRange < 0) throw new ArgumentOutOfRangeException(nameof(observationRange));
        this.observationChannels = (observationChannels ?? new[] { "territory", "watch" })
            .Where(channel => !string.IsNullOrWhiteSpace(channel))
            .Select(channel => channel.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();
        TerritorialPolicy = territorialPolicy ?? new FactionTerritorialPolicyDefinition();
        ContactStyle = string.IsNullOrWhiteSpace(contactStyle) ? null : contactStyle.Trim();
        LeadershipStyle = string.IsNullOrWhiteSpace(leadershipStyle) ? null : leadershipStyle.Trim();
        ObservationRange = observationRange;
    }

    public string Id { get; }
    public string Label { get; }
    public IReadOnlyList<string> Values => values;
    public IReadOnlyList<string> TabooActionTags => tabooActionTags;
    public FactionTerritorialPolicyDefinition TerritorialPolicy { get; }
    public string? ContactStyle { get; }
    public string? LeadershipStyle { get; }
    public int ObservationRange { get; }
    public IReadOnlyList<string> ObservationChannels => observationChannels;
}

/// <summary>Discoverable conduct preferences. Concrete territories and locations remain generated runtime state.</summary>
public sealed class FactionTerritorialPolicyDefinition
{
    private readonly List<string> permittedActionTags;
    private readonly List<string> restrictedActionTags;
    private readonly List<string> warningActionTags;

    public FactionTerritorialPolicyDefinition(
        IEnumerable<string>? permittedActionTags = null,
        IEnumerable<string>? restrictedActionTags = null,
        IEnumerable<string>? warningActionTags = null,
        FactionTerritorialPolicyResponseDefinition? warningResponse = null,
        FactionTerritorialPolicyResponseDefinition? restrictedResponse = null)
    {
        this.permittedActionTags = Normalize(permittedActionTags);
        this.restrictedActionTags = Normalize(restrictedActionTags);
        this.warningActionTags = Normalize(warningActionTags);
        WarningResponse = warningResponse ?? new FactionTerritorialPolicyResponseDefinition();
        RestrictedResponse = restrictedResponse ?? new FactionTerritorialPolicyResponseDefinition();
    }

    public IReadOnlyList<string> PermittedActionTags => permittedActionTags;
    public IReadOnlyList<string> RestrictedActionTags => restrictedActionTags;
    public IReadOnlyList<string> WarningActionTags => warningActionTags;
    public FactionTerritorialPolicyResponseDefinition WarningResponse { get; }
    public FactionTerritorialPolicyResponseDefinition RestrictedResponse { get; }

    private static List<string> Normalize(IEnumerable<string>? tags)
    {
        return (tags ?? Enumerable.Empty<string>())
            .Where(tag => !string.IsNullOrWhiteSpace(tag))
            .Select(tag => tag.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();
    }
}

/// <summary>Player-facing and simulation consequences for a generic territorial policy level.</summary>
public sealed class FactionTerritorialPolicyResponseDefinition
{
    public FactionTerritorialPolicyResponseDefinition(
        int trustDelta = 0,
        int angerDelta = 0,
        int fearDelta = 0,
        int awarenessIncrease = 0,
        string? eventTitle = null,
        string? eventBody = null,
        bool revealsFaction = false)
    {
        if (awarenessIncrease < 0) throw new ArgumentOutOfRangeException(nameof(awarenessIncrease));
        TrustDelta = trustDelta;
        AngerDelta = angerDelta;
        FearDelta = fearDelta;
        AwarenessIncrease = awarenessIncrease;
        EventTitle = string.IsNullOrWhiteSpace(eventTitle) ? null : eventTitle.Trim();
        EventBody = string.IsNullOrWhiteSpace(eventBody) ? null : eventBody.Trim();
        RevealsFaction = revealsFaction;
    }

    public int TrustDelta { get; }
    public int AngerDelta { get; }
    public int FearDelta { get; }
    public int AwarenessIncrease { get; }
    public string? EventTitle { get; }
    public string? EventBody { get; }
    public bool RevealsFaction { get; }
    public bool HasEffect => TrustDelta != 0 || AngerDelta != 0 || FearDelta != 0 || AwarenessIncrease != 0 || (EventTitle != null && EventBody != null);
}

public sealed class FactionProfileDefinitionSet
{
    private readonly Dictionary<string, FactionProfileDefinition> definitions;

    public FactionProfileDefinitionSet(IEnumerable<FactionProfileDefinition> definitions)
    {
        this.definitions = (definitions ?? throw new ArgumentNullException(nameof(definitions)))
            .ToDictionary(definition => definition.Id, StringComparer.Ordinal);
    }

    public FactionProfileDefinition? Find(string? id)
    {
        return !string.IsNullOrWhiteSpace(id) && definitions.TryGetValue(id, out var definition) ? definition : null;
    }

    public IReadOnlyCollection<FactionProfileDefinition> All => definitions.Values;
}

public sealed class WorldTriggerDefinition
{
    public WorldTriggerDefinition(string id, string? consequenceId = null)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Trigger id must not be empty.", nameof(id));
        Id = id.Trim();
        ConsequenceId = string.IsNullOrWhiteSpace(consequenceId) ? null : consequenceId.Trim();
    }

    public string Id { get; }
    public string? ConsequenceId { get; }
}

public sealed class ConsequenceStageDefinition
{
    private readonly List<string> situationDefinitionIds;
    private readonly List<WorldStageEffectDefinition> effects;

    public ConsequenceStageDefinition(
        string id,
        int delayDays,
        string? evidenceId,
        string? eventTitle,
        string? eventBody,
        IEnumerable<string>? situationDefinitionIds = null,
        IEnumerable<WorldStageEffectDefinition>? effects = null,
        WorldConsequenceSeverity severity = WorldConsequenceSeverity.Informational)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Consequence stage id must not be empty.", nameof(id));
        if (delayDays < 0) throw new ArgumentOutOfRangeException(nameof(delayDays));
        Id = id.Trim();
        DelayDays = delayDays;
        EvidenceId = string.IsNullOrWhiteSpace(evidenceId) ? null : evidenceId.Trim();
        EventTitle = string.IsNullOrWhiteSpace(eventTitle) ? null : eventTitle.Trim();
        EventBody = string.IsNullOrWhiteSpace(eventBody) ? null : eventBody.Trim();
        this.situationDefinitionIds = (situationDefinitionIds ?? Enumerable.Empty<string>())
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim())
            .Distinct(StringComparer.Ordinal)
            .ToList();
        this.effects = (effects ?? Enumerable.Empty<WorldStageEffectDefinition>()).ToList();
        if (this.effects.Select(effect => effect.Id).Distinct(StringComparer.Ordinal).Count() != this.effects.Count)
            throw new ArgumentException("World-stage effect IDs must be unique within one stage.", nameof(effects));
        Severity = severity;
    }

    public string Id { get; }
    public int DelayDays { get; }
    public string? EvidenceId { get; }
    public string? EventTitle { get; }
    public string? EventBody { get; }
    public IReadOnlyList<string> SituationDefinitionIds => situationDefinitionIds;
    public IReadOnlyList<WorldStageEffectDefinition> Effects => effects;
    public WorldConsequenceSeverity Severity { get; }
}

/// <summary>How urgent a process stage is. Serious stages require a preceding warning situation.</summary>
public enum WorldConsequenceSeverity
{
    Informational,
    Serious
}

/// <summary>Neutral, runtime-targeted world change authored by a consequence stage.</summary>
public enum WorldStageEffectKind
{
    AddEvidence,
    ChangeLocationState,
    SetLocationFlag,
    SetTilePassability,
    RaiseWorldTrigger,
    CreateSituation,
    EscalateRelatedFactionAwareness,
    CreateConnection
}

/// <summary>
/// Generic effect schema. It never contains a concrete faction or location ID: targets are the
/// source runtime location/coordinate or a generated relation attached to it.
/// </summary>
public sealed class WorldStageEffectDefinition
{
    private readonly List<string> actionTags;
    private readonly List<string> suppressIfSituationResponseTags;

    public WorldStageEffectDefinition(
        string id,
        WorldStageEffectKind kind,
        string? referenceId = null,
        string? stateChannel = null,
        string? stateId = null,
        bool? isBlocked = null,
        IEnumerable<string>? actionTags = null,
        int dueDays = 0,
        string? connectionKind = null,
        IEnumerable<string>? suppressIfSituationResponseTags = null)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("World-stage effect id must not be empty.", nameof(id));
        if (dueDays < 0) throw new ArgumentOutOfRangeException(nameof(dueDays));
        Id = id.Trim();
        Kind = kind;
        ReferenceId = string.IsNullOrWhiteSpace(referenceId) ? null : referenceId.Trim();
        StateChannel = string.IsNullOrWhiteSpace(stateChannel) ? null : stateChannel.Trim();
        StateId = string.IsNullOrWhiteSpace(stateId) ? null : stateId.Trim();
        IsBlocked = isBlocked;
        this.actionTags = (actionTags ?? Enumerable.Empty<string>()).Where(tag => !string.IsNullOrWhiteSpace(tag)).Select(tag => tag.Trim()).Distinct(StringComparer.Ordinal).ToList();
        DueDays = dueDays;
        ConnectionKind = string.IsNullOrWhiteSpace(connectionKind) ? null : connectionKind.Trim();
        this.suppressIfSituationResponseTags = (suppressIfSituationResponseTags ?? Enumerable.Empty<string>()).Where(tag => !string.IsNullOrWhiteSpace(tag)).Select(tag => tag.Trim()).Distinct(StringComparer.Ordinal).ToList();
    }

    public string Id { get; }
    public WorldStageEffectKind Kind { get; }
    public string? ReferenceId { get; }
    public string? StateChannel { get; }
    public string? StateId { get; }
    public bool? IsBlocked { get; }
    public IReadOnlyList<string> ActionTags => actionTags;
    public int DueDays { get; }
    public string? ConnectionKind { get; }
    public IReadOnlyList<string> SuppressIfSituationResponseTags => suppressIfSituationResponseTags;
}

/// <summary>An authored possible history. Its weight is read only once at process scheduling time.</summary>
public sealed class ConsequenceBranchDefinition
{
    private readonly Dictionary<string, ConsequenceStageDefinition> stages;

    public ConsequenceBranchDefinition(string id, int weight, IEnumerable<ConsequenceStageDefinition> stages)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Consequence branch id must not be empty.", nameof(id));
        if (weight < 1) throw new ArgumentOutOfRangeException(nameof(weight), "Consequence branch weight must be positive.");
        Id = id.Trim();
        Weight = weight;
        this.stages = (stages ?? throw new ArgumentNullException(nameof(stages)))
            .ToDictionary(stage => stage.Id, StringComparer.Ordinal);
        if (this.stages.Count == 0) throw new ArgumentException("A consequence branch needs at least one stage.", nameof(stages));
    }

    public string Id { get; }
    public int Weight { get; }
    public IReadOnlyCollection<ConsequenceStageDefinition> Stages => stages.Values;
    public ConsequenceStageDefinition? FindStage(string stageId) => stages.TryGetValue(stageId, out var stage) ? stage : null;
}

public sealed class ConsequenceDefinition
{
    private readonly Dictionary<string, ConsequenceBranchDefinition> branches;

    public ConsequenceDefinition(string id, IEnumerable<ConsequenceStageDefinition> stages)
        : this(id, new[] { new ConsequenceBranchDefinition("default", 1, stages) })
    {
    }

    public ConsequenceDefinition(string id, IEnumerable<ConsequenceBranchDefinition> branches)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Consequence id must not be empty.", nameof(id));
        Id = id.Trim();
        this.branches = (branches ?? throw new ArgumentNullException(nameof(branches))).ToDictionary(branch => branch.Id, StringComparer.Ordinal);
        if (this.branches.Count == 0) throw new ArgumentException("A consequence needs at least one branch.", nameof(branches));
    }

    public string Id { get; }
    public IReadOnlyCollection<ConsequenceBranchDefinition> Branches => branches.Values;
    /// <summary>Compatibility view for legacy callers and stage-only authoring.</summary>
    public IReadOnlyCollection<ConsequenceStageDefinition> Stages => branches.TryGetValue("default", out var branch)
        ? branch.Stages
        : branches.Values.SelectMany(item => item.Stages).ToArray();
    public ConsequenceBranchDefinition? FindBranch(string branchId) => branches.TryGetValue(branchId, out var branch) ? branch : null;
    public ConsequenceStageDefinition? FindStage(string branchId, string stageId) => FindBranch(branchId)?.FindStage(stageId);
    public ConsequenceStageDefinition? FindStage(string stageId) => FindBranch("default")?.FindStage(stageId);

    public ConsequenceBranchDefinition SelectBranch(IDeterministicRandomSource random)
    {
        if (random == null) throw new ArgumentNullException(nameof(random));
        var ordered = branches.Values.OrderBy(branch => branch.Id, StringComparer.Ordinal).ToList();
        if (ordered.Count == 1) return ordered[0];
        var total = ordered.Sum(branch => branch.Weight);
        var roll = random.NextInt(total);
        foreach (var branch in ordered)
        {
            if (roll < branch.Weight) return branch;
            roll -= branch.Weight;
        }

        throw new InvalidOperationException("Consequence branch selection did not resolve a branch.");
    }
}

public sealed class FactionReactionRuleDefinition
{
    private readonly HashSet<LocationFactionRelationKind> relationKinds;
    private readonly HashSet<string> requiredActionTags;
    private readonly HashSet<string> requiredFactionValues;
    private readonly HashSet<string> requiredFactionTabooTags;

    public FactionReactionRuleDefinition(
        string id,
        string triggerId,
        IEnumerable<LocationFactionRelationKind> relationKinds,
        FactionAwarenessLevel minimumAwareness,
        string? factionProfileId,
        int? minimumAnger,
        int? maximumTrust,
        int trustDelta,
        int angerDelta,
        int fearDelta,
        string? memoryId,
        string? eventTitle,
        string? eventBody,
        bool revealsFaction,
        int priority = 0,
        IEnumerable<string>? requiredActionTags = null,
        IEnumerable<string>? requiredFactionValues = null,
        IEnumerable<string>? requiredFactionTabooTags = null)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Reaction rule id must not be empty.", nameof(id));
        if (string.IsNullOrWhiteSpace(triggerId)) throw new ArgumentException("Reaction rule trigger id must not be empty.", nameof(triggerId));
        Id = id.Trim();
        TriggerId = triggerId.Trim();
        this.relationKinds = new HashSet<LocationFactionRelationKind>(relationKinds ?? throw new ArgumentNullException(nameof(relationKinds)));
        if (this.relationKinds.Count == 0) throw new ArgumentException("Reaction rule needs at least one relation kind.", nameof(relationKinds));
        this.requiredActionTags = new HashSet<string>((requiredActionTags ?? Enumerable.Empty<string>())
            .Where(tag => !string.IsNullOrWhiteSpace(tag))
            .Select(tag => tag.Trim()), StringComparer.Ordinal);
        this.requiredFactionValues = NormalizeTags(requiredFactionValues);
        this.requiredFactionTabooTags = NormalizeTags(requiredFactionTabooTags);
        MinimumAwareness = minimumAwareness;
        FactionProfileId = string.IsNullOrWhiteSpace(factionProfileId) ? null : factionProfileId.Trim();
        MinimumAnger = minimumAnger;
        MaximumTrust = maximumTrust;
        TrustDelta = trustDelta;
        AngerDelta = angerDelta;
        FearDelta = fearDelta;
        MemoryId = string.IsNullOrWhiteSpace(memoryId) ? null : memoryId.Trim();
        EventTitle = string.IsNullOrWhiteSpace(eventTitle) ? null : eventTitle.Trim();
        EventBody = string.IsNullOrWhiteSpace(eventBody) ? null : eventBody.Trim();
        RevealsFaction = revealsFaction;
        Priority = priority;
    }

    public string Id { get; }
    public string TriggerId { get; }
    public IReadOnlyCollection<LocationFactionRelationKind> RelationKinds => relationKinds;
    public IReadOnlyCollection<string> RequiredActionTags => requiredActionTags;
    public IReadOnlyCollection<string> RequiredFactionValues => requiredFactionValues;
    public IReadOnlyCollection<string> RequiredFactionTabooTags => requiredFactionTabooTags;
    public FactionAwarenessLevel MinimumAwareness { get; }
    public string? FactionProfileId { get; }
    public int? MinimumAnger { get; }
    public int? MaximumTrust { get; }
    public int TrustDelta { get; }
    public int AngerDelta { get; }
    public int FearDelta { get; }
    public string? MemoryId { get; }
    public string? EventTitle { get; }
    public string? EventBody { get; }
    public bool RevealsFaction { get; }
    public int Priority { get; }

    public bool Matches(
        FactionState faction,
        FactionProfileDefinition? profile,
        LocationFactionRelationState relation,
        FactionAwarenessLevel awareness,
        WorldTriggerState trigger)
    {
        return relationKinds.Contains(relation.Kind)
            && awareness >= MinimumAwareness
            && (FactionProfileId == null || FactionProfileId == faction.ReactionProfileId)
            && (!MinimumAnger.HasValue || faction.Anger >= MinimumAnger.Value)
            && (!MaximumTrust.HasValue || faction.Trust <= MaximumTrust.Value)
            && requiredActionTags.All(tag => trigger.ActionTags.Contains(tag, StringComparer.Ordinal))
            && requiredFactionValues.All(value => profile != null && profile.Values.Contains(value, StringComparer.Ordinal))
            && requiredFactionTabooTags.All(tag => profile != null && profile.TabooActionTags.Contains(tag, StringComparer.Ordinal));
    }

    private static HashSet<string> NormalizeTags(IEnumerable<string>? values)
    {
        return new HashSet<string>((values ?? Enumerable.Empty<string>())
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim()), StringComparer.Ordinal);
    }
}

public sealed class FactionTerritoryEntryRuleDefinition
{
    private readonly HashSet<string> requiredFactionValues;

    public FactionTerritoryEntryRuleDefinition(
        string id,
        string entryKind,
        string? factionProfileId,
        int trustDelta,
        int angerDelta,
        int fearDelta,
        bool promotesContact,
        bool revealsFaction,
        bool allowsInteraction,
        string? eventTitle,
        string? eventBody,
        int priority = 0,
        IEnumerable<string>? requiredFactionValues = null)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Territory entry rule id must not be empty.", nameof(id));
        if (entryKind != "territory" && entryKind != "warning") throw new ArgumentException("Entry kind must be territory or warning.", nameof(entryKind));
        Id = id.Trim();
        EntryKind = entryKind;
        FactionProfileId = string.IsNullOrWhiteSpace(factionProfileId) ? null : factionProfileId.Trim();
        TrustDelta = trustDelta;
        AngerDelta = angerDelta;
        FearDelta = fearDelta;
        PromotesContact = promotesContact;
        RevealsFaction = revealsFaction;
        AllowsInteraction = allowsInteraction;
        EventTitle = string.IsNullOrWhiteSpace(eventTitle) ? null : eventTitle.Trim();
        EventBody = string.IsNullOrWhiteSpace(eventBody) ? null : eventBody.Trim();
        Priority = priority;
        this.requiredFactionValues = new HashSet<string>((requiredFactionValues ?? Enumerable.Empty<string>())
            .Where(value => !string.IsNullOrWhiteSpace(value))
            .Select(value => value.Trim()), StringComparer.Ordinal);
    }

    public string Id { get; }
    public string EntryKind { get; }
    public string? FactionProfileId { get; }
    public int TrustDelta { get; }
    public int AngerDelta { get; }
    public int FearDelta { get; }
    public bool PromotesContact { get; }
    public bool RevealsFaction { get; }
    public bool AllowsInteraction { get; }
    public string? EventTitle { get; }
    public string? EventBody { get; }
    public int Priority { get; }
    public IReadOnlyCollection<string> RequiredFactionValues => requiredFactionValues;

    public bool Matches(FactionState faction, FactionProfileDefinition? profile, string entryKind)
    {
        return EntryKind == entryKind
            && (FactionProfileId == null || FactionProfileId == faction.ReactionProfileId)
            && requiredFactionValues.All(value => profile != null && profile.Values.Contains(value, StringComparer.Ordinal));
    }
}

public sealed class EvidenceDefinitionSet
{
    private readonly Dictionary<string, EvidenceDefinition> definitions;

    public EvidenceDefinitionSet(IEnumerable<EvidenceDefinition> definitions)
    {
        this.definitions = (definitions ?? throw new ArgumentNullException(nameof(definitions)))
            .ToDictionary(definition => definition.Id, StringComparer.Ordinal);
    }

    public EvidenceDefinition? Find(string? id)
    {
        return !string.IsNullOrWhiteSpace(id) && definitions.TryGetValue(id, out var definition) ? definition : null;
    }

    public IReadOnlyCollection<EvidenceDefinition> All => definitions.Values;
}

public sealed class FactionSignatureDefinitionSet
{
    private readonly Dictionary<string, FactionSignatureDefinition> definitions;

    public FactionSignatureDefinitionSet(IEnumerable<FactionSignatureDefinition> definitions)
    {
        this.definitions = (definitions ?? throw new ArgumentNullException(nameof(definitions)))
            .ToDictionary(definition => definition.Id, StringComparer.Ordinal);
    }

    public FactionSignatureDefinition? Find(string? id)
    {
        return !string.IsNullOrWhiteSpace(id) && definitions.TryGetValue(id, out var definition) ? definition : null;
    }

    public FactionSignatureDefinition? FindForProfile(string? profileId)
    {
        return string.IsNullOrWhiteSpace(profileId)
            ? null
            : definitions.Values.FirstOrDefault(item => item.ProfileId == profileId);
    }

    public IReadOnlyList<string> ProfileIds => definitions.Values
        .Select(item => item.ProfileId)
        .Distinct(StringComparer.Ordinal)
        .OrderBy(item => item, StringComparer.Ordinal)
        .ToList();

    public IReadOnlyCollection<FactionSignatureDefinition> All => definitions.Values;
}

public sealed class ScoutOutcomeRuleDefinition
{
    public ScoutOutcomeRuleDefinition(ScoutMissionBehavior behavior, ScoutMissionStatus whenStatus, ScoutMissionStatus outcome, ScoutMissionFocus? focus = null, string? missionTypeId = null)
    {
        Behavior = behavior;
        WhenStatus = whenStatus;
        Outcome = outcome;
        Focus = focus;
        MissionTypeId = string.IsNullOrWhiteSpace(missionTypeId) ? null : missionTypeId.Trim();
    }

    public ScoutMissionBehavior Behavior { get; }
    public ScoutMissionStatus WhenStatus { get; }
    public ScoutMissionStatus Outcome { get; }
    public ScoutMissionFocus? Focus { get; }
    public string? MissionTypeId { get; }
    public bool Matches(ScoutMissionState mission) => Behavior == mission.Behavior && WhenStatus == mission.Status && (!Focus.HasValue || Focus.Value == mission.Focus) && (MissionTypeId == null || MissionTypeId == mission.MissionTypeId);
}

/// <summary>JSON-authored order constraints for a scout mission category.</summary>
public sealed class ScoutMissionTypeDefinition
{
    private readonly HashSet<ScoutMissionFocus> allowedFocuses;

    public ScoutMissionTypeDefinition(
        string id,
        string label,
        int minDurationDays,
        int maxDurationDays,
        int maxScouts,
        IEnumerable<ScoutMissionFocus> allowedFocuses)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Scout mission type id must not be empty.", nameof(id));
        if (string.IsNullOrWhiteSpace(label)) throw new ArgumentException("Scout mission type label must not be empty.", nameof(label));
        if (minDurationDays < 1 || maxDurationDays < minDurationDays) throw new ArgumentOutOfRangeException(nameof(maxDurationDays));
        if (maxScouts < 1) throw new ArgumentOutOfRangeException(nameof(maxScouts));
        Id = id.Trim();
        Label = label.Trim();
        MinDurationDays = minDurationDays;
        MaxDurationDays = maxDurationDays;
        MaxScouts = maxScouts;
        this.allowedFocuses = new HashSet<ScoutMissionFocus>(allowedFocuses ?? throw new ArgumentNullException(nameof(allowedFocuses)));
        if (this.allowedFocuses.Count == 0) throw new ArgumentException("Scout mission type needs at least one focus.", nameof(allowedFocuses));
    }

    public string Id { get; }
    public string Label { get; }
    public int MinDurationDays { get; }
    public int MaxDurationDays { get; }
    public int MaxScouts { get; }
    public IReadOnlyCollection<ScoutMissionFocus> AllowedFocuses => allowedFocuses;
    public bool Allows(ScoutMissionFocus focus) => allowedFocuses.Contains(focus);
}

/// <summary>Presentation and compatibility metadata for one reusable scout focus.</summary>
public sealed class ScoutFocusDefinition
{
    private readonly HashSet<string> compatibleMissionTypeIds;

    public ScoutFocusDefinition(ScoutMissionFocus focus, string label, string description, IEnumerable<string>? compatibleMissionTypeIds = null)
    {
        if (string.IsNullOrWhiteSpace(label)) throw new ArgumentException("Scout focus label must not be empty.", nameof(label));
        if (string.IsNullOrWhiteSpace(description)) throw new ArgumentException("Scout focus description must not be empty.", nameof(description));
        Focus = focus;
        Label = label.Trim();
        Description = description.Trim();
        compatibleMissionTypeIds = compatibleMissionTypeIds ?? Enumerable.Empty<string>();
        this.compatibleMissionTypeIds = new HashSet<string>(compatibleMissionTypeIds
            .Where(id => !string.IsNullOrWhiteSpace(id))
            .Select(id => id.Trim()), StringComparer.Ordinal);
    }

    public ScoutMissionFocus Focus { get; }
    public string Label { get; }
    public string Description { get; }
    public IReadOnlyCollection<string> CompatibleMissionTypeIds => compatibleMissionTypeIds;
    public bool Allows(string missionTypeId) => compatibleMissionTypeIds.Count == 0 || compatibleMissionTypeIds.Contains(missionTypeId);
}

public sealed class ScoutReportTemplateDefinition
{
    public ScoutReportTemplateDefinition(ScoutMissionFocus focus, ScoutMissionStatus outcome, string title, string body, string hint, string? missionTypeId = null)
    {
        Focus = focus;
        Outcome = outcome;
        Title = Require(title, nameof(title));
        Body = Require(body, nameof(body));
        Hint = Require(hint, nameof(hint));
        MissionTypeId = string.IsNullOrWhiteSpace(missionTypeId) ? null : missionTypeId.Trim();
    }

    public ScoutMissionFocus Focus { get; }
    public ScoutMissionStatus Outcome { get; }
    public string Title { get; }
    public string Body { get; }
    public string Hint { get; }
    public string? MissionTypeId { get; }

    private static string Require(string value, string name)
    {
        if (string.IsNullOrWhiteSpace(value)) throw new ArgumentException("Value must not be empty.", name);
        return value.Trim();
    }
}

public sealed class ScoutContentDefinitionSet
{
    private readonly List<ScoutOutcomeRuleDefinition> outcomeRules;
    private readonly List<ScoutReportTemplateDefinition> reportTemplates;
    private readonly Dictionary<string, ScoutMissionTypeDefinition> missionTypes;
    private readonly Dictionary<ScoutMissionFocus, ScoutFocusDefinition> focuses;

    public ScoutContentDefinitionSet(
        IEnumerable<ScoutOutcomeRuleDefinition>? outcomeRules = null,
        IEnumerable<ScoutReportTemplateDefinition>? reportTemplates = null,
        IEnumerable<ScoutMissionTypeDefinition>? missionTypes = null,
        IEnumerable<ScoutFocusDefinition>? focuses = null)
    {
        this.outcomeRules = (outcomeRules ?? Enumerable.Empty<ScoutOutcomeRuleDefinition>()).ToList();
        this.reportTemplates = (reportTemplates ?? Enumerable.Empty<ScoutReportTemplateDefinition>()).ToList();
        this.missionTypes = (missionTypes ?? Enumerable.Empty<ScoutMissionTypeDefinition>()).ToDictionary(definition => definition.Id, StringComparer.Ordinal);
        this.focuses = (focuses ?? Enumerable.Empty<ScoutFocusDefinition>()).ToDictionary(definition => definition.Focus);
    }

    public ScoutOutcomeRuleDefinition? FindOutcome(ScoutMissionState mission)
    {
        return outcomeRules.FirstOrDefault(rule => rule.Matches(mission) && rule.Focus.HasValue)
            ?? outcomeRules.FirstOrDefault(rule => rule.Matches(mission));
    }

    public ScoutReportTemplateDefinition? FindReport(ScoutMissionState mission, ScoutMissionStatus outcome)
    {
        return reportTemplates.FirstOrDefault(template => template.Focus == mission.Focus && template.Outcome == outcome && template.MissionTypeId == mission.MissionTypeId)
            ?? reportTemplates.FirstOrDefault(template => template.Focus == mission.Focus && template.Outcome == outcome && template.MissionTypeId == null);
    }

    public ScoutMissionTypeDefinition? FindMissionType(string? id)
    {
        return !string.IsNullOrWhiteSpace(id) && missionTypes.TryGetValue(id, out var definition) ? definition : null;
    }

    public ScoutFocusDefinition? FindFocus(ScoutMissionFocus focus)
    {
        return focuses.TryGetValue(focus, out var definition) ? definition : null;
    }

    public bool HasMissionTypeDefinitions => missionTypes.Count > 0;
    public IReadOnlyCollection<ScoutMissionTypeDefinition> MissionTypes => missionTypes.Values;
    public IReadOnlyCollection<ScoutFocusDefinition> Focuses => focuses.Values;
}

public sealed class CrossSystemDataBundle
{
    public CrossSystemDataBundle(
        EvidenceDefinitionSet evidence,
        IEnumerable<FactionSignatureDefinition>? factionSignatures = null,
        IEnumerable<FactionProfileDefinition>? factionProfiles = null,
        ScoutContentDefinitionSet? scoutContent = null,
        IEnumerable<WorldTriggerDefinition>? triggers = null,
        IEnumerable<ConsequenceDefinition>? consequences = null,
        IEnumerable<FactionReactionRuleDefinition>? factionReactionRules = null,
        IEnumerable<FactionTerritoryEntryRuleDefinition>? factionTerritoryEntryRules = null)
    {
        Evidence = evidence ?? throw new ArgumentNullException(nameof(evidence));
        FactionSignatures = new FactionSignatureDefinitionSet(factionSignatures ?? Enumerable.Empty<FactionSignatureDefinition>());
        FactionProfiles = new FactionProfileDefinitionSet(factionProfiles ?? Enumerable.Empty<FactionProfileDefinition>());
        ScoutContent = scoutContent ?? new ScoutContentDefinitionSet();
        Triggers = (triggers ?? Enumerable.Empty<WorldTriggerDefinition>()).ToDictionary(trigger => trigger.Id, StringComparer.Ordinal);
        Consequences = (consequences ?? Enumerable.Empty<ConsequenceDefinition>()).ToDictionary(consequence => consequence.Id, StringComparer.Ordinal);
        FactionReactionRules = (factionReactionRules ?? Enumerable.Empty<FactionReactionRuleDefinition>()).ToList();
        FactionTerritoryEntryRules = (factionTerritoryEntryRules ?? Enumerable.Empty<FactionTerritoryEntryRuleDefinition>()).ToList();
    }

    public EvidenceDefinitionSet Evidence { get; }
    public FactionSignatureDefinitionSet FactionSignatures { get; }
    public FactionProfileDefinitionSet FactionProfiles { get; }
    public ScoutContentDefinitionSet ScoutContent { get; }
    public IReadOnlyDictionary<string, WorldTriggerDefinition> Triggers { get; }
    public IReadOnlyDictionary<string, ConsequenceDefinition> Consequences { get; }
    public IReadOnlyList<FactionReactionRuleDefinition> FactionReactionRules { get; }
    public IReadOnlyList<FactionTerritoryEntryRuleDefinition> FactionTerritoryEntryRules { get; }
    public WorldTriggerDefinition? FindTrigger(string id) => Triggers.TryGetValue(id, out var trigger) ? trigger : null;
    public ConsequenceDefinition? FindConsequence(string id) => Consequences.TryGetValue(id, out var consequence) ? consequence : null;
}

/// <summary>
/// Loads the cross-system content that is shared by world generation, scouting and later reaction
/// resolution. Runtime world state stores only stable definition IDs, never authored player text.
/// </summary>
public static class CrossSystemDataLoader
{
    private const int MinimumSupportedSchemaVersion = 1;
    private const int MaximumSupportedSchemaVersion = 2;
    private static readonly HashSet<string> SupportedDocumentTypes = new(StringComparer.Ordinal)
    {
        "evidence-definitions",
        "world-trigger-definitions",
        "consequence-definitions",
        "faction-signatures",
        "faction-profiles",
        "faction-reaction-rules",
        "faction-territory-entry-rules",
        "scout-mission-types",
        "scout-focuses",
        "scout-outcome-rules",
        "scout-report-templates"
    };

    public static CrossSystemDataBundle? LoadFromDirectory(string rootFolder)
    {
        if (string.IsNullOrWhiteSpace(rootFolder) || !Directory.Exists(rootFolder)) return null;

        return LoadFromDirectories(new[] { rootFolder });
    }

    public static CrossSystemDataBundle? LoadFromDirectories(IEnumerable<string> rootFolders)
    {
        if (rootFolders == null) throw new ArgumentNullException(nameof(rootFolders));
        var documents = rootFolders
            .Where(root => !string.IsNullOrWhiteSpace(root) && Directory.Exists(root))
            .SelectMany(root => Directory.EnumerateFiles(root, "*.json", SearchOption.AllDirectories))
            .OrderBy(path => path, StringComparer.Ordinal)
            .Where(IsSupportedDocumentFile)
            .Select(File.ReadAllText)
            .ToList();
        return documents.Count == 0 ? null : LoadFromJson(documents);
    }

    // Direct directory loading remains available for tests and older callers. It must not consume
    // schema-v2 authoring documents that are owned by CrossSystemAuthoringDataLoader.
    private static bool IsSupportedDocumentFile(string path)
    {
        try
        {
            var document = JObject.Parse(File.ReadAllText(path));
            return SupportedDocumentTypes.Contains((string?)document["documentType"] ?? string.Empty);
        }
        catch (JsonException ex)
        {
            throw new LocationDataException($"Malformed cross-system JSON document '{path}': {ex.Message}");
        }
    }

    public static CrossSystemDataBundle LoadFromJson(IEnumerable<string> jsonDocuments)
    {
        if (jsonDocuments == null) throw new ArgumentNullException(nameof(jsonDocuments));
        var evidence = new List<EvidenceDefinitionDto>();
        var triggers = new List<WorldTriggerDefinitionDto>();
        var consequences = new List<ConsequenceDefinitionDto>();
        var factionSignatures = new List<FactionSignatureDefinitionDto>();
        var factionProfiles = new List<FactionProfileDefinitionDto>();
        var factionReactionRules = new List<FactionReactionRuleDto>();
        var factionTerritoryEntryRules = new List<FactionTerritoryEntryRuleDto>();
        var scoutMissionTypes = new List<ScoutMissionTypeDto>();
        var scoutFocuses = new List<ScoutFocusDto>();
        var scoutOutcomeRules = new List<ScoutOutcomeRuleDto>();
        var scoutReportTemplates = new List<ScoutReportTemplateDto>();

        foreach (var json in jsonDocuments)
        {
            JObject envelope;
            try
            {
                envelope = JObject.Parse(json);
            }
            catch (JsonException ex)
            {
                throw new LocationDataException($"Malformed cross-system JSON document: {ex.Message}");
            }

            var schemaVersion = (int?)envelope["schemaVersion"] ?? 0;
            if (schemaVersion < MinimumSupportedSchemaVersion || schemaVersion > MaximumSupportedSchemaVersion)
            {
                throw new LocationDataException($"Unsupported schemaVersion '{schemaVersion}' (supported: {MinimumSupportedSchemaVersion}-{MaximumSupportedSchemaVersion}).");
            }

            var items = envelope["items"] as JArray ?? new JArray();
            switch ((string?)envelope["documentType"])
            {
                case "evidence-definitions": evidence.AddRange(items.ToObject<List<EvidenceDefinitionDto>>()!); break;
                case "world-trigger-definitions": triggers.AddRange(items.ToObject<List<WorldTriggerDefinitionDto>>()!); break;
                case "consequence-definitions": consequences.AddRange(items.ToObject<List<ConsequenceDefinitionDto>>()!); break;
                case "faction-signatures": factionSignatures.AddRange(items.ToObject<List<FactionSignatureDefinitionDto>>()!); break;
                case "faction-profiles": factionProfiles.AddRange(items.ToObject<List<FactionProfileDefinitionDto>>()!); break;
                case "faction-reaction-rules": factionReactionRules.AddRange(items.ToObject<List<FactionReactionRuleDto>>()!); break;
                case "faction-territory-entry-rules": factionTerritoryEntryRules.AddRange(items.ToObject<List<FactionTerritoryEntryRuleDto>>()!); break;
                case "scout-mission-types": scoutMissionTypes.AddRange(items.ToObject<List<ScoutMissionTypeDto>>()!); break;
                case "scout-focuses": scoutFocuses.AddRange(items.ToObject<List<ScoutFocusDto>>()!); break;
                case "scout-outcome-rules": scoutOutcomeRules.AddRange(items.ToObject<List<ScoutOutcomeRuleDto>>()!); break;
                case "scout-report-templates": scoutReportTemplates.AddRange(items.ToObject<List<ScoutReportTemplateDto>>()!); break;
                case "world-generation-presets": break;
                case "world-generation-option-presets": break;
                default: throw new LocationDataException($"Unsupported cross-system documentType '{(string?)envelope["documentType"]}'.");
            }
        }

        var definitions = evidence.Select(item => new EvidenceDefinition(Require(item.Id, "evidence.id"), Require(item.ScoutReportText, "evidence.scoutReportText"), item.WorldEventText, item.SymbolId)).ToList();
        if (definitions.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Cross-system evidence IDs must be unique.");
        }

        var builtSignatures = factionSignatures
            .Select(item => new FactionSignatureDefinition(Require(item.Id, "factionSignature.id"), Require(item.ProfileId, "factionSignature.profileId"), Require(item.Label, "factionSignature.label")))
            .ToList();
        if (builtSignatures.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Faction signature IDs must be unique.");
        }
        if (definitions.Any(definition => definition.SymbolId != null && !builtSignatures.Any(signature => signature.Id == definition.SymbolId)))
        {
            throw new LocationDataException("Evidence references an unknown faction signature.");
        }

        var builtFactionProfiles = factionProfiles
            .Select(item => new FactionProfileDefinition(
                Require(item.Id, "factionProfile.id"),
                Require(item.Label, "factionProfile.label"),
                item.Values,
                item.TabooActionTags,
                BuildTerritorialPolicy(item.TerritorialPolicy),
                item.ContactStyle,
                item.LeadershipStyle,
                item.ObservationRange,
                item.ObservationChannels))
            .ToList();
        if (builtFactionProfiles.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Faction profile IDs must be unique.");
        }

        var builtConsequences = consequences.Select(item => new ConsequenceDefinition(
            Require(item.Id, "consequence.id"),
            BuildConsequenceBranches(item))).ToList();
        if (builtConsequences.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Cross-system consequence IDs must be unique.");
        }
        if (builtConsequences.SelectMany(consequence => consequence.Branches).SelectMany(branch => branch.Stages)
            .Any(stage => stage.EvidenceId != null && !definitions.Any(evidenceDefinition => evidenceDefinition.Id == stage.EvidenceId)))
        {
            throw new LocationDataException("A consequence stage references an unknown evidence definition.");
        }
        if (builtConsequences.SelectMany(consequence => consequence.Branches).SelectMany(branch => branch.Stages).SelectMany(stage => stage.Effects)
            .Any(effect => effect.Kind == WorldStageEffectKind.AddEvidence && (effect.ReferenceId == null || !definitions.Any(evidenceDefinition => evidenceDefinition.Id == effect.ReferenceId))))
        {
            throw new LocationDataException("A world-stage evidence effect references an unknown evidence definition.");
        }
        if (builtConsequences.SelectMany(consequence => consequence.Branches).SelectMany(branch => branch.Stages).SelectMany(stage => stage.Effects)
            .Any(effect => effect.Kind == WorldStageEffectKind.ChangeLocationState && (effect.StateChannel == null || effect.StateId == null)))
        {
            throw new LocationDataException("A location-state world-stage effect requires stateChannel and stateId.");
        }
        if (builtConsequences.SelectMany(consequence => consequence.Branches).SelectMany(branch => branch.Stages).SelectMany(stage => stage.Effects)
            .Any(effect => effect.Kind == WorldStageEffectKind.SetTilePassability && !effect.IsBlocked.HasValue))
        {
            throw new LocationDataException("A tile-passability world-stage effect requires isBlocked.");
        }

        var builtTriggers = triggers.Select(item => new WorldTriggerDefinition(Require(item.Id, "trigger.id"), item.ConsequenceId)).ToList();
        if (builtTriggers.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Cross-system trigger IDs must be unique.");
        }
        if (builtTriggers.Any(trigger => trigger.ConsequenceId != null && !builtConsequences.Any(consequence => consequence.Id == trigger.ConsequenceId)))
        {
            throw new LocationDataException("A world trigger references an unknown consequence definition.");
        }

        var builtReactionRules = factionReactionRules.Select(BuildFactionReactionRule).ToList();
        if (builtReactionRules.GroupBy(rule => rule.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Faction reaction rule IDs must be unique.");
        }
        if (builtReactionRules.Any(rule => !builtTriggers.Any(trigger => trigger.Id == rule.TriggerId)))
        {
            throw new LocationDataException("A faction reaction rule references an unknown world trigger.");
        }
        if (builtReactionRules.Any(rule => rule.FactionProfileId != null && !builtFactionProfiles.Any(profile => profile.Id == rule.FactionProfileId)))
        {
            throw new LocationDataException("A faction reaction rule references an unknown faction profile.");
        }
        if (builtReactionRules.Any(rule => rule.RequiredFactionValues.Any(value => !builtFactionProfiles.Any(profile => profile.Values.Contains(value, StringComparer.Ordinal)))))
        {
            throw new LocationDataException("A faction reaction rule references an unknown faction value.");
        }
        if (builtReactionRules.Any(rule => rule.RequiredFactionTabooTags.Any(tag => !builtFactionProfiles.Any(profile => profile.TabooActionTags.Contains(tag, StringComparer.Ordinal)))))
        {
            throw new LocationDataException("A faction reaction rule references an unknown faction taboo action tag.");
        }

        var builtTerritoryEntryRules = factionTerritoryEntryRules.Select(BuildFactionTerritoryEntryRule).ToList();
        if (builtTerritoryEntryRules.GroupBy(rule => rule.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Faction territory entry rule IDs must be unique.");
        }
        if (builtTerritoryEntryRules.Any(rule => rule.FactionProfileId != null && !builtFactionProfiles.Any(profile => profile.Id == rule.FactionProfileId)))
        {
            throw new LocationDataException("A faction territory entry rule references an unknown faction profile.");
        }
        if (builtTerritoryEntryRules.Any(rule => rule.RequiredFactionValues.Any(value => !builtFactionProfiles.Any(profile => profile.Values.Contains(value, StringComparer.Ordinal)))))
        {
            throw new LocationDataException("A faction territory entry rule references an unknown faction value.");
        }

        var builtScoutMissionTypes = scoutMissionTypes.Select(item => new ScoutMissionTypeDefinition(
            Require(item.Id, "scoutMissionType.id"),
            Require(item.Label, "scoutMissionType.label"),
            item.MinDurationDays,
            item.MaxDurationDays,
            item.MaxScouts,
            (item.AllowedFocuses ?? new List<string>())
                .Select(focus => ParseEnum<ScoutMissionFocus>(focus, "scoutMissionType.allowedFocuses")))).ToList();
        if (builtScoutMissionTypes.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Scout mission type IDs must be unique.");
        }

        var builtScoutFocuses = scoutFocuses.Select(item => new ScoutFocusDefinition(
            ParseEnum<ScoutMissionFocus>(Require(item.Id, "scoutFocus.id"), "scoutFocus.id"),
            Require(item.Label, "scoutFocus.label"),
            Require(item.Description, "scoutFocus.description"),
            item.CompatibleMissionTypeIds)).ToList();
        if (builtScoutFocuses.GroupBy(item => item.Focus).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Scout focus IDs must be unique.");
        }
        if (builtScoutMissionTypes.Count > 0 && builtScoutFocuses.Count == 0)
        {
            throw new LocationDataException("Scout mission types require scout focus definitions.");
        }
        if (builtScoutMissionTypes.Any(mission => mission.AllowedFocuses.Any(focus => !builtScoutFocuses.Any(definition => definition.Focus == focus))))
        {
            throw new LocationDataException("Scout mission type references an unknown scout focus.");
        }
        if (builtScoutFocuses.Any(focus => focus.CompatibleMissionTypeIds.Any(id => !builtScoutMissionTypes.Any(mission => mission.Id == id))))
        {
            throw new LocationDataException("Scout focus references an unknown scout mission type.");
        }
        if (builtScoutMissionTypes.Any(mission => mission.AllowedFocuses.Any(focus => !builtScoutFocuses.First(definition => definition.Focus == focus).Allows(mission.Id))))
        {
            throw new LocationDataException("Scout mission type and scout focus compatibility disagree.");
        }

        var builtScoutOutcomes = scoutOutcomeRules.Select(item => new ScoutOutcomeRuleDefinition(
            ParseEnum<ScoutMissionBehavior>(Require(item.Behavior, "scoutOutcome.behavior"), "scoutOutcome.behavior"),
            ParseEnum<ScoutMissionStatus>(Require(item.WhenStatus, "scoutOutcome.whenStatus"), "scoutOutcome.whenStatus"),
            ParseEnum<ScoutMissionStatus>(Require(item.Outcome, "scoutOutcome.outcome"), "scoutOutcome.outcome"),
            string.IsNullOrWhiteSpace(item.Focus) ? null : ParseEnum<ScoutMissionFocus>(Require(item.Focus, "scoutOutcome.focus"), "scoutOutcome.focus"), item.MissionTypeId)).ToList();
        var builtScoutReports = scoutReportTemplates.Select(item => new ScoutReportTemplateDefinition(
            ParseEnum<ScoutMissionFocus>(Require(item.Focus, "scoutReport.focus"), "scoutReport.focus"),
            ParseEnum<ScoutMissionStatus>(Require(item.Outcome, "scoutReport.outcome"), "scoutReport.outcome"),
            Require(item.Title, "scoutReport.title"), Require(item.Body, "scoutReport.body"), Require(item.Hint, "scoutReport.hint"), item.MissionTypeId)).ToList();

        if (builtScoutMissionTypes.Count > 0 && (builtScoutOutcomes.Any(rule => rule.MissionTypeId != null && !builtScoutMissionTypes.Any(mission => mission.Id == rule.MissionTypeId))
            || builtScoutReports.Any(template => template.MissionTypeId != null && !builtScoutMissionTypes.Any(mission => mission.Id == template.MissionTypeId))))
        {
            throw new LocationDataException("Scout content references an unknown scout mission type.");
        }

        return new CrossSystemDataBundle(new EvidenceDefinitionSet(definitions), builtSignatures, builtFactionProfiles, new ScoutContentDefinitionSet(builtScoutOutcomes, builtScoutReports, builtScoutMissionTypes, builtScoutFocuses), builtTriggers, builtConsequences, builtReactionRules, builtTerritoryEntryRules);
    }

    private static IReadOnlyList<ConsequenceBranchDefinition> BuildConsequenceBranches(ConsequenceDefinitionDto dto)
    {
        if (dto.Branches != null && dto.Branches.Count > 0)
        {
            if (dto.Stages != null && dto.Stages.Count > 0)
            {
                throw new LocationDataException("A consequence definition must use either legacy stages or explicit branches, not both.");
            }

            return dto.Branches.Select(branch => new ConsequenceBranchDefinition(
                Require(branch.Id, "consequence.branch.id"),
                branch.Weight,
                BuildConsequenceStages(branch.Stages))).ToList();
        }

        return new[]
        {
            new ConsequenceBranchDefinition("default", 1, BuildConsequenceStages(dto.Stages))
        };
    }

    private static IReadOnlyList<ConsequenceStageDefinition> BuildConsequenceStages(IEnumerable<ConsequenceStageDto>? stages)
    {
        return (stages ?? Enumerable.Empty<ConsequenceStageDto>())
            .Select(stage =>
            {
                var stageId = Require(stage.Id, "consequence.stage.id");
                var effects = (stage.Effects ?? new List<WorldStageEffectDto>())
                    .Select((effect, index) => BuildWorldStageEffect(effect, stageId, index))
                    .ToList();

                // Schema-v1 fields remain a concise authoring form and are translated into the
                // same generic effect pipeline as schema-v2 effect objects.
                if (!string.IsNullOrWhiteSpace(stage.EvidenceId))
                    effects.Add(new WorldStageEffectDefinition($"legacy-evidence:{stageId}", WorldStageEffectKind.AddEvidence, stage.EvidenceId));
                foreach (var situationId in stage.SituationCandidateIds ?? new List<string>())
                    effects.Add(new WorldStageEffectDefinition($"legacy-situation:{stageId}:{situationId}", WorldStageEffectKind.CreateSituation, situationId));

                return new ConsequenceStageDefinition(
                    stageId,
                    stage.DelayDays,
                    stage.EvidenceId,
                    stage.Event?.Title,
                    stage.Event?.Body,
                    stage.SituationCandidateIds,
                    effects,
                    ParseEnum(stage.Severity, WorldConsequenceSeverity.Informational));
            })
            .ToList();
    }

    private static WorldStageEffectDefinition BuildWorldStageEffect(WorldStageEffectDto dto, string stageId, int index)
    {
        var id = string.IsNullOrWhiteSpace(dto.Id) ? $"effect:{stageId}:{index + 1}" : dto.Id;
        return new WorldStageEffectDefinition(
            id,
            ParseEnum<WorldStageEffectKind>(Require(dto.Kind, "consequence.stage.effect.kind"), "consequence.stage.effect.kind"),
            dto.ReferenceId,
            dto.StateChannel,
            dto.StateId,
            dto.IsBlocked,
            dto.ActionTags,
            dto.DueDays,
            dto.ConnectionKind,
            dto.SuppressIfSituationResponseTags);
    }

    private static FactionReactionRuleDefinition BuildFactionReactionRule(FactionReactionRuleDto dto)
    {
        var relationKinds = (dto.RelationKinds ?? new List<string>()).Select(value => ParseEnum<LocationFactionRelationKind>(value, "reactionRule.relationKinds"));
        return new FactionReactionRuleDefinition(
            Require(dto.Id, "reactionRule.id"),
            Require(dto.TriggerId, "reactionRule.triggerId"),
            relationKinds,
            ParseEnum(dto.MinimumAwareness, FactionAwarenessLevel.Unaware),
            dto.FactionProfileId,
            dto.MinimumAnger,
            dto.MaximumTrust,
            dto.TrustDelta,
            dto.AngerDelta,
            dto.FearDelta,
            dto.MemoryId,
            dto.Event?.Title,
            dto.Event?.Body,
            dto.Event?.RevealsFaction ?? false,
            dto.Priority,
            dto.RequiredActionTags,
            dto.RequiredFactionValues,
            dto.RequiredFactionTabooTags);
    }

    private static FactionTerritoryEntryRuleDefinition BuildFactionTerritoryEntryRule(FactionTerritoryEntryRuleDto dto)
    {
        return new FactionTerritoryEntryRuleDefinition(
            Require(dto.Id, "territoryEntryRule.id"),
            Require(dto.EntryKind, "territoryEntryRule.entryKind").ToLowerInvariant(),
            dto.FactionProfileId,
            dto.TrustDelta,
            dto.AngerDelta,
            dto.FearDelta,
            dto.PromotesContact,
            dto.Event?.RevealsFaction ?? false,
            dto.Event?.AllowsInteraction ?? false,
            dto.Event?.Title,
            dto.Event?.Body,
            dto.Priority,
            dto.RequiredFactionValues);
    }

    private static FactionTerritorialPolicyDefinition BuildTerritorialPolicy(FactionTerritorialPolicyDto? dto)
    {
        return new FactionTerritorialPolicyDefinition(
            dto?.PermittedActionTags,
            dto?.RestrictedActionTags,
            dto?.WarningActionTags,
            BuildTerritorialPolicyResponse(dto?.WarningResponse),
            BuildTerritorialPolicyResponse(dto?.RestrictedResponse));
    }

    private static FactionTerritorialPolicyResponseDefinition BuildTerritorialPolicyResponse(FactionTerritorialPolicyResponseDto? dto)
    {
        return new FactionTerritorialPolicyResponseDefinition(
            dto?.TrustDelta ?? 0,
            dto?.AngerDelta ?? 0,
            dto?.FearDelta ?? 0,
            dto?.AwarenessIncrease ?? 0,
            dto?.Event?.Title,
            dto?.Event?.Body,
            dto?.Event?.RevealsFaction ?? false);
    }

    private static string Require(string? value, string field)
    {
        if (string.IsNullOrWhiteSpace(value)) throw new LocationDataException($"Missing required field '{field}'.");
        return value.Trim();
    }

    private static TEnum ParseEnum<TEnum>(string? value, TEnum defaultValue) where TEnum : struct, Enum
    {
        if (string.IsNullOrWhiteSpace(value)) return defaultValue;
        if (Enum.TryParse<TEnum>(value, true, out var parsed)) return parsed;
        throw new LocationDataException($"Unknown enum value '{value}'.");
    }

    private static TEnum ParseEnum<TEnum>(string value, string field) where TEnum : struct, Enum
    {
        if (Enum.TryParse<TEnum>(value, true, out var parsed)) return parsed;
        throw new LocationDataException($"Unknown value '{value}' for '{field}'.");
    }

    private sealed class EvidenceDefinitionDto
    {
        public string? Id { get; set; }
        public string? ScoutReportText { get; set; }
        public string? WorldEventText { get; set; }
        public string? SymbolId { get; set; }
    }

    private sealed class FactionSignatureDefinitionDto
    {
        public string? Id { get; set; }
        public string? ProfileId { get; set; }
        public string? Label { get; set; }
    }

    private sealed class FactionProfileDefinitionDto
    {
        public string? Id { get; set; }
        public string? Label { get; set; }
        public List<string>? Values { get; set; }
        public List<string>? TabooActionTags { get; set; }
        public FactionTerritorialPolicyDto? TerritorialPolicy { get; set; }
        public string? ContactStyle { get; set; }
        public string? LeadershipStyle { get; set; }
        public int ObservationRange { get; set; }
        public List<string>? ObservationChannels { get; set; }
    }

    private sealed class FactionTerritorialPolicyDto
    {
        public List<string>? PermittedActionTags { get; set; }
        public List<string>? RestrictedActionTags { get; set; }
        public List<string>? WarningActionTags { get; set; }
        public FactionTerritorialPolicyResponseDto? WarningResponse { get; set; }
        public FactionTerritorialPolicyResponseDto? RestrictedResponse { get; set; }
    }

    private sealed class FactionTerritorialPolicyResponseDto
    {
        public int? TrustDelta { get; set; }
        public int? AngerDelta { get; set; }
        public int? FearDelta { get; set; }
        public int? AwarenessIncrease { get; set; }
        public FactionReactionEventDto? Event { get; set; }
    }

    private sealed class WorldTriggerDefinitionDto
    {
        public string? Id { get; set; }
        public string? ConsequenceId { get; set; }
    }

    private sealed class ConsequenceDefinitionDto
    {
        public string? Id { get; set; }
        public List<ConsequenceStageDto>? Stages { get; set; }
        public List<ConsequenceBranchDto>? Branches { get; set; }
    }

    private sealed class ConsequenceBranchDto
    {
        public string? Id { get; set; }
        public int Weight { get; set; }
        public List<ConsequenceStageDto>? Stages { get; set; }
    }

    private sealed class ConsequenceStageDto
    {
        public string? Id { get; set; }
        public int DelayDays { get; set; }
        public string? EvidenceId { get; set; }
        public ConsequenceEventDto? Event { get; set; }
        public List<string>? SituationCandidateIds { get; set; }
        public List<WorldStageEffectDto>? Effects { get; set; }
        public string? Severity { get; set; }
    }

    private sealed class WorldStageEffectDto
    {
        public string? Id { get; set; }
        public string? Kind { get; set; }
        public string? ReferenceId { get; set; }
        public string? StateChannel { get; set; }
        public string? StateId { get; set; }
        public bool? IsBlocked { get; set; }
        public List<string>? ActionTags { get; set; }
        public int DueDays { get; set; }
        public string? ConnectionKind { get; set; }
        public List<string>? SuppressIfSituationResponseTags { get; set; }
    }

    private sealed class ConsequenceEventDto
    {
        public string? Title { get; set; }
        public string? Body { get; set; }
    }

    private sealed class FactionReactionRuleDto
    {
        public string? Id { get; set; }
        public string? TriggerId { get; set; }
        public List<string>? RelationKinds { get; set; }
        public string? MinimumAwareness { get; set; }
        public string? FactionProfileId { get; set; }
        public int? MinimumAnger { get; set; }
        public int? MaximumTrust { get; set; }
        public int TrustDelta { get; set; }
        public int AngerDelta { get; set; }
        public int FearDelta { get; set; }
        public string? MemoryId { get; set; }
        public FactionReactionEventDto? Event { get; set; }
        public int Priority { get; set; }
        public List<string>? RequiredActionTags { get; set; }
        public List<string>? RequiredFactionValues { get; set; }
        public List<string>? RequiredFactionTabooTags { get; set; }
    }

    private sealed class FactionReactionEventDto
    {
        public string? Title { get; set; }
        public string? Body { get; set; }
        public bool RevealsFaction { get; set; }
    }

    private sealed class FactionTerritoryEntryRuleDto
    {
        public string? Id { get; set; }
        public string? EntryKind { get; set; }
        public string? FactionProfileId { get; set; }
        public int TrustDelta { get; set; }
        public int AngerDelta { get; set; }
        public int FearDelta { get; set; }
        public bool PromotesContact { get; set; }
        public FactionTerritoryEntryEventDto? Event { get; set; }
        public int Priority { get; set; }
        public List<string>? RequiredFactionValues { get; set; }
    }

    private sealed class FactionTerritoryEntryEventDto
    {
        public string? Title { get; set; }
        public string? Body { get; set; }
        public bool RevealsFaction { get; set; }
        public bool AllowsInteraction { get; set; }
    }

    private sealed class ScoutOutcomeRuleDto
    {
        public string? Behavior { get; set; }
        public string? WhenStatus { get; set; }
        public string? Outcome { get; set; }
        public string? Focus { get; set; }
        public string? MissionTypeId { get; set; }
    }

    private sealed class ScoutMissionTypeDto
    {
        public string? Id { get; set; }
        public string? Label { get; set; }
        public int MinDurationDays { get; set; }
        public int MaxDurationDays { get; set; }
        public int MaxScouts { get; set; }
        public List<string>? AllowedFocuses { get; set; }
    }

    private sealed class ScoutFocusDto
    {
        public string? Id { get; set; }
        public string? Label { get; set; }
        public string? Description { get; set; }
        public List<string>? CompatibleMissionTypeIds { get; set; }
    }

    private sealed class ScoutReportTemplateDto
    {
        public string? Focus { get; set; }
        public string? MissionTypeId { get; set; }
        public string? Outcome { get; set; }
        public string? Title { get; set; }
        public string? Body { get; set; }
        public string? Hint { get; set; }
    }
}
}
