#nullable enable
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Game.Core;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;

namespace Game.App
{

/// <summary>JSON-authored text and metadata for evidence generated by cross-system simulation.</summary>
public sealed class EvidenceDefinition
{
    public EvidenceDefinition(string id, string scoutReportText, string? worldEventText = null)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Evidence id must not be empty.", nameof(id));
        if (string.IsNullOrWhiteSpace(scoutReportText)) throw new ArgumentException("Scout report text must not be empty.", nameof(scoutReportText));
        Id = id.Trim();
        ScoutReportText = scoutReportText.Trim();
        WorldEventText = string.IsNullOrWhiteSpace(worldEventText) ? null : worldEventText.Trim();
    }

    public string Id { get; }
    public string ScoutReportText { get; }
    public string? WorldEventText { get; }
}

public sealed class WorldTriggerDefinition
{
    public WorldTriggerDefinition(string id, string? consequenceId = null)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Trigger id must not be empty.", nameof(id));
        Id = id.Trim();
        ConsequenceId = string.IsNullOrWhiteSpace(consequenceId) ? null : consequenceId.Trim();
    }

    public string Id { get; }
    public string? ConsequenceId { get; }
}

public sealed class ConsequenceStageDefinition
{
    public ConsequenceStageDefinition(string id, int delayDays, string? evidenceId, string? eventTitle, string? eventBody)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Consequence stage id must not be empty.", nameof(id));
        if (delayDays < 0) throw new ArgumentOutOfRangeException(nameof(delayDays));
        Id = id.Trim();
        DelayDays = delayDays;
        EvidenceId = string.IsNullOrWhiteSpace(evidenceId) ? null : evidenceId.Trim();
        EventTitle = string.IsNullOrWhiteSpace(eventTitle) ? null : eventTitle.Trim();
        EventBody = string.IsNullOrWhiteSpace(eventBody) ? null : eventBody.Trim();
    }

    public string Id { get; }
    public int DelayDays { get; }
    public string? EvidenceId { get; }
    public string? EventTitle { get; }
    public string? EventBody { get; }
}

public sealed class ConsequenceDefinition
{
    private readonly Dictionary<string, ConsequenceStageDefinition> stages;

    public ConsequenceDefinition(string id, IEnumerable<ConsequenceStageDefinition> stages)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Consequence id must not be empty.", nameof(id));
        Id = id.Trim();
        this.stages = (stages ?? throw new ArgumentNullException(nameof(stages))).ToDictionary(stage => stage.Id, StringComparer.Ordinal);
        if (this.stages.Count == 0) throw new ArgumentException("A consequence needs at least one stage.", nameof(stages));
    }

    public string Id { get; }
    public IReadOnlyCollection<ConsequenceStageDefinition> Stages => stages.Values;
    public ConsequenceStageDefinition? FindStage(string stageId) => stages.TryGetValue(stageId, out var stage) ? stage : null;
}

public sealed class FactionReactionRuleDefinition
{
    private readonly HashSet<LocationFactionRelationKind> relationKinds;

    public FactionReactionRuleDefinition(
        string id,
        string triggerId,
        IEnumerable<LocationFactionRelationKind> relationKinds,
        FactionAwarenessLevel minimumAwareness,
        string? factionProfileId,
        int? minimumAnger,
        int? maximumTrust,
        int trustDelta,
        int angerDelta,
        int fearDelta,
        string? memoryId,
        string? eventTitle,
        string? eventBody,
        bool revealsFaction,
        int priority = 0)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Reaction rule id must not be empty.", nameof(id));
        if (string.IsNullOrWhiteSpace(triggerId)) throw new ArgumentException("Reaction rule trigger id must not be empty.", nameof(triggerId));
        Id = id.Trim();
        TriggerId = triggerId.Trim();
        this.relationKinds = new HashSet<LocationFactionRelationKind>(relationKinds ?? throw new ArgumentNullException(nameof(relationKinds)));
        if (this.relationKinds.Count == 0) throw new ArgumentException("Reaction rule needs at least one relation kind.", nameof(relationKinds));
        MinimumAwareness = minimumAwareness;
        FactionProfileId = string.IsNullOrWhiteSpace(factionProfileId) ? null : factionProfileId.Trim();
        MinimumAnger = minimumAnger;
        MaximumTrust = maximumTrust;
        TrustDelta = trustDelta;
        AngerDelta = angerDelta;
        FearDelta = fearDelta;
        MemoryId = string.IsNullOrWhiteSpace(memoryId) ? null : memoryId.Trim();
        EventTitle = string.IsNullOrWhiteSpace(eventTitle) ? null : eventTitle.Trim();
        EventBody = string.IsNullOrWhiteSpace(eventBody) ? null : eventBody.Trim();
        RevealsFaction = revealsFaction;
        Priority = priority;
    }

    public string Id { get; }
    public string TriggerId { get; }
    public IReadOnlyCollection<LocationFactionRelationKind> RelationKinds => relationKinds;
    public FactionAwarenessLevel MinimumAwareness { get; }
    public string? FactionProfileId { get; }
    public int? MinimumAnger { get; }
    public int? MaximumTrust { get; }
    public int TrustDelta { get; }
    public int AngerDelta { get; }
    public int FearDelta { get; }
    public string? MemoryId { get; }
    public string? EventTitle { get; }
    public string? EventBody { get; }
    public bool RevealsFaction { get; }
    public int Priority { get; }

    public bool Matches(FactionState faction, LocationFactionRelationState relation, FactionAwarenessLevel awareness)
    {
        return relationKinds.Contains(relation.Kind)
            && awareness >= MinimumAwareness
            && (FactionProfileId == null || FactionProfileId == faction.ReactionProfileId)
            && (!MinimumAnger.HasValue || faction.Anger >= MinimumAnger.Value)
            && (!MaximumTrust.HasValue || faction.Trust <= MaximumTrust.Value);
    }
}

public sealed class FactionTerritoryEntryRuleDefinition
{
    public FactionTerritoryEntryRuleDefinition(
        string id,
        string entryKind,
        string? factionProfileId,
        int trustDelta,
        int angerDelta,
        int fearDelta,
        bool promotesContact,
        bool revealsFaction,
        bool allowsInteraction,
        string? eventTitle,
        string? eventBody,
        int priority = 0)
    {
        if (string.IsNullOrWhiteSpace(id)) throw new ArgumentException("Territory entry rule id must not be empty.", nameof(id));
        if (entryKind != "territory" && entryKind != "warning") throw new ArgumentException("Entry kind must be territory or warning.", nameof(entryKind));
        Id = id.Trim();
        EntryKind = entryKind;
        FactionProfileId = string.IsNullOrWhiteSpace(factionProfileId) ? null : factionProfileId.Trim();
        TrustDelta = trustDelta;
        AngerDelta = angerDelta;
        FearDelta = fearDelta;
        PromotesContact = promotesContact;
        RevealsFaction = revealsFaction;
        AllowsInteraction = allowsInteraction;
        EventTitle = string.IsNullOrWhiteSpace(eventTitle) ? null : eventTitle.Trim();
        EventBody = string.IsNullOrWhiteSpace(eventBody) ? null : eventBody.Trim();
        Priority = priority;
    }

    public string Id { get; }
    public string EntryKind { get; }
    public string? FactionProfileId { get; }
    public int TrustDelta { get; }
    public int AngerDelta { get; }
    public int FearDelta { get; }
    public bool PromotesContact { get; }
    public bool RevealsFaction { get; }
    public bool AllowsInteraction { get; }
    public string? EventTitle { get; }
    public string? EventBody { get; }
    public int Priority { get; }

    public bool Matches(FactionState faction, string entryKind)
    {
        return EntryKind == entryKind && (FactionProfileId == null || FactionProfileId == faction.ReactionProfileId);
    }
}

public sealed class EvidenceDefinitionSet
{
    private readonly Dictionary<string, EvidenceDefinition> definitions;

    public EvidenceDefinitionSet(IEnumerable<EvidenceDefinition> definitions)
    {
        this.definitions = (definitions ?? throw new ArgumentNullException(nameof(definitions)))
            .ToDictionary(definition => definition.Id, StringComparer.Ordinal);
    }

    public EvidenceDefinition? Find(string? id)
    {
        return !string.IsNullOrWhiteSpace(id) && definitions.TryGetValue(id, out var definition) ? definition : null;
    }

    public IReadOnlyCollection<EvidenceDefinition> All => definitions.Values;
}

public sealed class CrossSystemDataBundle
{
    public CrossSystemDataBundle(
        EvidenceDefinitionSet evidence,
        IEnumerable<WorldTriggerDefinition>? triggers = null,
        IEnumerable<ConsequenceDefinition>? consequences = null,
        IEnumerable<FactionReactionRuleDefinition>? factionReactionRules = null,
        IEnumerable<FactionTerritoryEntryRuleDefinition>? factionTerritoryEntryRules = null)
    {
        Evidence = evidence ?? throw new ArgumentNullException(nameof(evidence));
        Triggers = (triggers ?? Enumerable.Empty<WorldTriggerDefinition>()).ToDictionary(trigger => trigger.Id, StringComparer.Ordinal);
        Consequences = (consequences ?? Enumerable.Empty<ConsequenceDefinition>()).ToDictionary(consequence => consequence.Id, StringComparer.Ordinal);
        FactionReactionRules = (factionReactionRules ?? Enumerable.Empty<FactionReactionRuleDefinition>()).ToList();
        FactionTerritoryEntryRules = (factionTerritoryEntryRules ?? Enumerable.Empty<FactionTerritoryEntryRuleDefinition>()).ToList();
    }

    public EvidenceDefinitionSet Evidence { get; }
    public IReadOnlyDictionary<string, WorldTriggerDefinition> Triggers { get; }
    public IReadOnlyDictionary<string, ConsequenceDefinition> Consequences { get; }
    public IReadOnlyList<FactionReactionRuleDefinition> FactionReactionRules { get; }
    public IReadOnlyList<FactionTerritoryEntryRuleDefinition> FactionTerritoryEntryRules { get; }
    public WorldTriggerDefinition? FindTrigger(string id) => Triggers.TryGetValue(id, out var trigger) ? trigger : null;
    public ConsequenceDefinition? FindConsequence(string id) => Consequences.TryGetValue(id, out var consequence) ? consequence : null;
}

/// <summary>
/// Loads the cross-system content that is shared by world generation, scouting and later reaction
/// resolution. Runtime world state stores only stable definition IDs, never authored player text.
/// </summary>
public static class CrossSystemDataLoader
{
    private const int SupportedSchemaVersion = 1;

    public static CrossSystemDataBundle? LoadFromDirectory(string rootFolder)
    {
        if (string.IsNullOrWhiteSpace(rootFolder) || !Directory.Exists(rootFolder)) return null;

        return LoadFromDirectories(new[] { rootFolder });
    }

    public static CrossSystemDataBundle? LoadFromDirectories(IEnumerable<string> rootFolders)
    {
        if (rootFolders == null) throw new ArgumentNullException(nameof(rootFolders));
        var documents = rootFolders
            .Where(root => !string.IsNullOrWhiteSpace(root) && Directory.Exists(root))
            .SelectMany(root => Directory.EnumerateFiles(root, "*.json", SearchOption.AllDirectories))
            .OrderBy(path => path, StringComparer.Ordinal)
            .Select(File.ReadAllText)
            .ToList();
        return documents.Count == 0 ? null : LoadFromJson(documents);
    }

    public static CrossSystemDataBundle LoadFromJson(IEnumerable<string> jsonDocuments)
    {
        if (jsonDocuments == null) throw new ArgumentNullException(nameof(jsonDocuments));
        var evidence = new List<EvidenceDefinitionDto>();
        var triggers = new List<WorldTriggerDefinitionDto>();
        var consequences = new List<ConsequenceDefinitionDto>();
        var factionReactionRules = new List<FactionReactionRuleDto>();
        var factionTerritoryEntryRules = new List<FactionTerritoryEntryRuleDto>();

        foreach (var json in jsonDocuments)
        {
            JObject envelope;
            try
            {
                envelope = JObject.Parse(json);
            }
            catch (JsonException ex)
            {
                throw new LocationDataException($"Malformed cross-system JSON document: {ex.Message}");
            }

            var schemaVersion = (int?)envelope["schemaVersion"] ?? 0;
            if (schemaVersion != SupportedSchemaVersion)
            {
                throw new LocationDataException($"Unsupported schemaVersion '{schemaVersion}' (expected {SupportedSchemaVersion}).");
            }

            var items = envelope["items"] as JArray ?? new JArray();
            switch ((string?)envelope["documentType"])
            {
                case "evidence-definitions": evidence.AddRange(items.ToObject<List<EvidenceDefinitionDto>>()!); break;
                case "world-trigger-definitions": triggers.AddRange(items.ToObject<List<WorldTriggerDefinitionDto>>()!); break;
                case "consequence-definitions": consequences.AddRange(items.ToObject<List<ConsequenceDefinitionDto>>()!); break;
                case "faction-reaction-rules": factionReactionRules.AddRange(items.ToObject<List<FactionReactionRuleDto>>()!); break;
                case "faction-territory-entry-rules": factionTerritoryEntryRules.AddRange(items.ToObject<List<FactionTerritoryEntryRuleDto>>()!); break;
                case "world-generation-presets": break;
                case "world-generation-option-presets": break;
                default: throw new LocationDataException($"Unsupported cross-system documentType '{(string?)envelope["documentType"]}'.");
            }
        }

        var definitions = evidence.Select(item => new EvidenceDefinition(Require(item.Id, "evidence.id"), Require(item.ScoutReportText, "evidence.scoutReportText"), item.WorldEventText)).ToList();
        if (definitions.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Cross-system evidence IDs must be unique.");
        }

        var builtConsequences = consequences.Select(item => new ConsequenceDefinition(
            Require(item.Id, "consequence.id"),
            (item.Stages ?? new List<ConsequenceStageDto>()).Select(stage => new ConsequenceStageDefinition(
                Require(stage.Id, "consequence.stage.id"), stage.DelayDays, stage.EvidenceId, stage.Event?.Title, stage.Event?.Body)))).ToList();
        if (builtConsequences.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Cross-system consequence IDs must be unique.");
        }
        if (builtConsequences.SelectMany(consequence => consequence.Stages)
            .Any(stage => stage.EvidenceId != null && !definitions.Any(evidenceDefinition => evidenceDefinition.Id == stage.EvidenceId)))
        {
            throw new LocationDataException("A consequence stage references an unknown evidence definition.");
        }

        var builtTriggers = triggers.Select(item => new WorldTriggerDefinition(Require(item.Id, "trigger.id"), item.ConsequenceId)).ToList();
        if (builtTriggers.GroupBy(item => item.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Cross-system trigger IDs must be unique.");
        }
        if (builtTriggers.Any(trigger => trigger.ConsequenceId != null && !builtConsequences.Any(consequence => consequence.Id == trigger.ConsequenceId)))
        {
            throw new LocationDataException("A world trigger references an unknown consequence definition.");
        }

        var builtReactionRules = factionReactionRules.Select(BuildFactionReactionRule).ToList();
        if (builtReactionRules.GroupBy(rule => rule.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Faction reaction rule IDs must be unique.");
        }
        if (builtReactionRules.Any(rule => !builtTriggers.Any(trigger => trigger.Id == rule.TriggerId)))
        {
            throw new LocationDataException("A faction reaction rule references an unknown world trigger.");
        }

        var builtTerritoryEntryRules = factionTerritoryEntryRules.Select(BuildFactionTerritoryEntryRule).ToList();
        if (builtTerritoryEntryRules.GroupBy(rule => rule.Id, StringComparer.Ordinal).Any(group => group.Count() > 1))
        {
            throw new LocationDataException("Faction territory entry rule IDs must be unique.");
        }

        return new CrossSystemDataBundle(new EvidenceDefinitionSet(definitions), builtTriggers, builtConsequences, builtReactionRules, builtTerritoryEntryRules);
    }

    private static FactionReactionRuleDefinition BuildFactionReactionRule(FactionReactionRuleDto dto)
    {
        var relationKinds = (dto.RelationKinds ?? new List<string>()).Select(value => ParseEnum<LocationFactionRelationKind>(value, "reactionRule.relationKinds"));
        return new FactionReactionRuleDefinition(
            Require(dto.Id, "reactionRule.id"),
            Require(dto.TriggerId, "reactionRule.triggerId"),
            relationKinds,
            ParseEnum(dto.MinimumAwareness, FactionAwarenessLevel.Unaware),
            dto.FactionProfileId,
            dto.MinimumAnger,
            dto.MaximumTrust,
            dto.TrustDelta,
            dto.AngerDelta,
            dto.FearDelta,
            dto.MemoryId,
            dto.Event?.Title,
            dto.Event?.Body,
            dto.Event?.RevealsFaction ?? false,
            dto.Priority);
    }

    private static FactionTerritoryEntryRuleDefinition BuildFactionTerritoryEntryRule(FactionTerritoryEntryRuleDto dto)
    {
        return new FactionTerritoryEntryRuleDefinition(
            Require(dto.Id, "territoryEntryRule.id"),
            Require(dto.EntryKind, "territoryEntryRule.entryKind").ToLowerInvariant(),
            dto.FactionProfileId,
            dto.TrustDelta,
            dto.AngerDelta,
            dto.FearDelta,
            dto.PromotesContact,
            dto.Event?.RevealsFaction ?? false,
            dto.Event?.AllowsInteraction ?? false,
            dto.Event?.Title,
            dto.Event?.Body,
            dto.Priority);
    }

    private static string Require(string? value, string field)
    {
        if (string.IsNullOrWhiteSpace(value)) throw new LocationDataException($"Missing required field '{field}'.");
        return value.Trim();
    }

    private static TEnum ParseEnum<TEnum>(string? value, TEnum defaultValue) where TEnum : struct, Enum
    {
        if (string.IsNullOrWhiteSpace(value)) return defaultValue;
        if (Enum.TryParse<TEnum>(value, true, out var parsed)) return parsed;
        throw new LocationDataException($"Unknown enum value '{value}'.");
    }

    private static TEnum ParseEnum<TEnum>(string value, string field) where TEnum : struct, Enum
    {
        if (Enum.TryParse<TEnum>(value, true, out var parsed)) return parsed;
        throw new LocationDataException($"Unknown value '{value}' for '{field}'.");
    }

    private sealed class EvidenceDefinitionDto
    {
        public string? Id { get; set; }
        public string? ScoutReportText { get; set; }
        public string? WorldEventText { get; set; }
    }

    private sealed class WorldTriggerDefinitionDto
    {
        public string? Id { get; set; }
        public string? ConsequenceId { get; set; }
    }

    private sealed class ConsequenceDefinitionDto
    {
        public string? Id { get; set; }
        public List<ConsequenceStageDto>? Stages { get; set; }
    }

    private sealed class ConsequenceStageDto
    {
        public string? Id { get; set; }
        public int DelayDays { get; set; }
        public string? EvidenceId { get; set; }
        public ConsequenceEventDto? Event { get; set; }
    }

    private sealed class ConsequenceEventDto
    {
        public string? Title { get; set; }
        public string? Body { get; set; }
    }

    private sealed class FactionReactionRuleDto
    {
        public string? Id { get; set; }
        public string? TriggerId { get; set; }
        public List<string>? RelationKinds { get; set; }
        public string? MinimumAwareness { get; set; }
        public string? FactionProfileId { get; set; }
        public int? MinimumAnger { get; set; }
        public int? MaximumTrust { get; set; }
        public int TrustDelta { get; set; }
        public int AngerDelta { get; set; }
        public int FearDelta { get; set; }
        public string? MemoryId { get; set; }
        public FactionReactionEventDto? Event { get; set; }
        public int Priority { get; set; }
    }

    private sealed class FactionReactionEventDto
    {
        public string? Title { get; set; }
        public string? Body { get; set; }
        public bool RevealsFaction { get; set; }
    }

    private sealed class FactionTerritoryEntryRuleDto
    {
        public string? Id { get; set; }
        public string? EntryKind { get; set; }
        public string? FactionProfileId { get; set; }
        public int TrustDelta { get; set; }
        public int AngerDelta { get; set; }
        public int FearDelta { get; set; }
        public bool PromotesContact { get; set; }
        public FactionTerritoryEntryEventDto? Event { get; set; }
        public int Priority { get; set; }
    }

    private sealed class FactionTerritoryEntryEventDto
    {
        public string? Title { get; set; }
        public string? Body { get; set; }
        public bool RevealsFaction { get; set; }
        public bool AllowsInteraction { get; set; }
    }
}
}
